# 全般的な設定
AllCops:
  TargetRubyVersion: 3.1  # Rubyのバージョン指定
  # SuggestExtensions: false  # メッセージを表示しない
  Exclude:  # チェック対象外
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/*.rb'

# クラスとモジュールにトップレベルのドキュメントを強制しない
Style/Documentation:
  Enabled: false

# マジックコメント #frozen_string_literal: true を強制しない
Style/FrozenStringLiteralComment:
  Enabled: false

# 配列やハッシュなどのリテラルは凍結されていることを強制しない
Style/MutableConstant:
  Enabled: false

# シンボルで構成された配列リテラルは %i 記法を強制しない
Style/SymbolArray:
  Enabled: false

# ソースコード内の末尾の空白行と最後の改行を強制しない。
Layout/TrailingEmptyLines:
  Enabled: false

# 比較演算子の使用を許可する
Style/NumericPredicate:
  Enabled: false

# メソッドのパラメータ名をチェックしない
Naming/MethodParameterName:
  Enabled: false